name: coinin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  # l10n
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  # navigation
  auto_route: ^10.1.0+1

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  #state management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  #network
  dio: ^5.8.0+1
  dio_http_formatter: ^3.3.0
  http_parser: ^4.1.2

  #helpers
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  logger: ^2.6.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  flutter_svg: ^2.2.0
  permission_handler: ^12.0.1


  #UI
  another_flushbar: ^1.12.30


  #database
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  auto_route_generator: ^10.2.3
  injectable_generator: ^2.7.0
  freezed: ^3.0.6
  flutter_gen_runner:


flutter_gen:
  output: lib/generated/
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true

flutter_intl:
  main_locale: en
  enabled: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/icons/bottom_bar/
    - assets/icons/home_page/
    - assets/images/
    - assets/images/home_page/
    - assets/fonts/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf


